name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout working branch
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Npm
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-node-
      
      - name: Install node-prune
        run: curl -sf https://gobinaries.com/tj/node-prune | sh
      
      - name: Install dependencies
        run: npm install

      - name: Install gatsby-cli
        run: npm install -g gatsby-cli

      - name: Build Gatsby dev site
        run: gatsby build